# Generated by Django 5.1.4 on 2025-01-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inc_exp_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
